"""init

Revision ID: 7c22eaa59d34
Revises: 
Create Date: 2026-06-16 23:13:51.372160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7c22eaa59d34'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('heroes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localized_name', sa.String(length=100), nullable=False),
    sa.Column('primary_attr', sa.String(length=3), nullable=True),
    sa.Column('attack_type', sa.String(length=10), nullable=True),
    sa.Column('roles', sa.JSON(), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('localized_name', sa.String(length=100), nullable=True),
    sa.Column('cost', sa.Integer(), nullable=True),
    sa.Column('img', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('matches',
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.BigInteger(), nullable=True),
    sa.Column('game_mode', sa.SmallInteger(), nullable=True),
    sa.Column('lobby_type', sa.SmallInteger(), nullable=True),
    sa.Column('radiant_win', sa.Boolean(), nullable=True),
    sa.Column('patch', sa.SmallInteger(), nullable=True),
    sa.Column('region', sa.SmallInteger(), nullable=True),
    sa.Column('avg_mmr', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('players',
    sa.Column('steam_id', sa.BigInteger(), nullable=False),
    sa.Column('persona_name', sa.String(length=255), nullable=True),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('profile_url', sa.String(length=500), nullable=True),
    sa.Column('country_code', sa.String(length=5), nullable=True),
    sa.Column('rank_tier', sa.Integer(), nullable=True),
    sa.Column('leaderboard_rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('steam_id')
    )
    op.create_table('match_players',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.BigInteger(), nullable=False),
    sa.Column('steam_id', sa.BigInteger(), nullable=True),
    sa.Column('hero_id', sa.Integer(), nullable=True),
    sa.Column('slot', sa.SmallInteger(), nullable=True),
    sa.Column('is_radiant', sa.Boolean(), nullable=True),
    sa.Column('win', sa.Boolean(), nullable=True),
    sa.Column('level', sa.SmallInteger(), nullable=True),
    sa.Column('kills', sa.SmallInteger(), nullable=False),
    sa.Column('deaths', sa.SmallInteger(), nullable=False),
    sa.Column('assists', sa.SmallInteger(), nullable=False),
    sa.Column('gold_per_min', sa.Integer(), nullable=False),
    sa.Column('xp_per_min', sa.Integer(), nullable=False),
    sa.Column('last_hits', sa.Integer(), nullable=False),
    sa.Column('denies', sa.Integer(), nullable=False),
    sa.Column('net_worth', sa.Integer(), nullable=False),
    sa.Column('hero_damage', sa.Integer(), nullable=False),
    sa.Column('tower_damage', sa.Integer(), nullable=False),
    sa.Column('hero_healing', sa.Integer(), nullable=False),
    sa.Column('item_0', sa.Integer(), nullable=True),
    sa.Column('item_1', sa.Integer(), nullable=True),
    sa.Column('item_2', sa.Integer(), nullable=True),
    sa.Column('item_3', sa.Integer(), nullable=True),
    sa.Column('item_4', sa.Integer(), nullable=True),
    sa.Column('item_5', sa.Integer(), nullable=True),
    sa.Column('backpack_0', sa.Integer(), nullable=True),
    sa.Column('backpack_1', sa.Integer(), nullable=True),
    sa.Column('backpack_2', sa.Integer(), nullable=True),
    sa.Column('neutral_item', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['hero_id'], ['heroes.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ),
    sa.ForeignKeyConstraint(['steam_id'], ['players.steam_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_players_match_id'), 'match_players', ['match_id'], unique=False)
    op.create_index(op.f('ix_match_players_steam_id'), 'match_players', ['steam_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_players_steam_id'), table_name='match_players')
    op.drop_index(op.f('ix_match_players_match_id'), table_name='match_players')
    op.drop_table('match_players')
    op.drop_table('players')
    op.drop_table('matches')
    op.drop_table('items')
    op.drop_table('heroes')
    # ### end Alembic commands ###
